---
title: 'The Adolescent Emotional Brain and Physical Outbursts'
subtitle: "writeup - PSYC593"
csl: apa.csl
format:
  pdf: 
    latex-output-dir: "../../documents/"
  html:
    embed-resources: true
    self_contained: true 
    output_dir: "../../doc/"
knitr: 
  opts_chunk:
      fig.path: "../../results/"
editor: source
markdown: 
    wrap: 72
author: Maddy and Biraj
date: today
---

# Background

The adolescence is a period in human development where increased autonomy, sense of identity, forming of social circles, and risk-taking behaviors emerge within a defined age group. It is during these times when emotions override rational decision-making abilities and become the primary mover in, at the time, important choices that can significantly impact the youth’s biopsychosocial construct that they have knit together to what they perceive as reality.

This is also when the adolescent begins to develop a stronger sense of right and wrong, usually accompanied by the newfound concept of consequences, legalities (e.g., pairing well with risk-taking behaviors including underaged drug and alcohol use), chronic positive or negative emotional states (e.g., constant fear, panic, or built-up stress is symptomatic of anxiety), among other feelings of self-concept and self-esteem that are challenged by themselves or their peers. Ultimately, the individual tends to fall into a state of greater vulnerability which becomes more opportune for themselves or others to attack the inner self of their emerging identity.

# Statement of Problem

The teenage years are often stigmatized for negative factors such as bullying (physical, social, emotional), evolving mental health disorders (e.g., Major Depressive Disorder), peer pressure, and decreased physical health (e.g., poor sleep, diet, and exercise). These concerns are counterbalanced by the increased autonomy, responsibility, and freedom often seen during adolescence. Teenagers may obtain driving permits, begin working, lead clubs, volunteer, and spend more time with friends or in romantic relationships.

Amid this emotional roller-coaster, exacerbated by environmental factors (home, school, religion) and genetics (family history of mental illness), abnormal behaviors can emerge more frequently and severely.

# Research Question

This research seeks to understand the relationship between mental (e.g., suicide ideation, loneliness), social (e.g., bullying), and lifestyle behaviors (e.g., drug and alcohol use) with physical outbursts in adolescence. Specifically, the research question is: **Are mental, social, and lifestyle behaviors associated with physical outbursts in adolescence?**

# Data

The sample dataset in which this research question will be asked is with from the Global School-Based Student Health Survey (GSHS) from Afghanistan, Bangladesh, Bhutan, The Maldives, Nepal, and Sri Lanka. This was a collaborative surveillance project between the selected national governments and the World Health Organization (WHO) to help countries measure and assess the behavioral risk factors and protective factors in the adolescent population aged 13 to 17 years.

# Variables Description

The following table outlines the variables used in the analysis, the survey questions they correspond to, and the recoding method used:

| Variable                      | Survey Question                                                                                            | Recoding                                                |
|----------------|-------------------------------|--------------------------|
| **Parents understanding**     | "During the past 30 days, how often did your parents/guardians understand your problems and worries?"      | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Parents monitoring**        | "During the past 30 days, how often did your parents/guardians know what you were doing with free time?"   | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Parents check homework**    | "During the past 30 days, how often did your parents/guardians check if your homework was done?"           | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Parents Control**           | "During the past 30 days, how often did your parents/guardians go through your things without permission?" | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Gender**                    | "What is your sex?"                                                                                        | 1 = Male, 2 = Female                                    |
| **Age**                       | "How old are you?"                                                                                         | 13-15 = 1, 16-17 = 2                                    |
| **Current cigarette smoking** | "During the past 30 days, on how many days did you smoke cigarettes?"                                      | 0 = No, 1 or more = Yes                                 |
| **Currently drank alcohol**   | "During the past 30 days, how many drinks did you usually drink per day?"                                  | 0 = No, 1 or more = Yes                                 |
| **Currently used marijuana**  | "During the past 30 days, how many times have you used marijuana?"                                         | 0 = No, 1 or more = Yes                                 |
| **Ever used amphetamines**    | "During your life, how many times have you used amphetamines or methamphetamines?"                         | 0 = No, 1 or more = Yes                                 |
| **Physical Activity**         | "During the past 7 days, how many days were you physically active for at least 60 minutes?"                | 0 = No, 1 or more days = Yes                            |
| **PE Class Attendance**       | "During this school year, how many days did you attend physical education (PE) class each week?"           | 0 = No, 1 or more days = Yes                            |
| **Sedentary behavior**        | "How much time do you spend watching TV, playing games, or talking with friends daily?"                    | Less than 1-2 hours = No, 3 or more hours = Yes         |
| **Supportive friends**        | "During the past 30 days, how often were students kind and helpful?"                                       | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Close friends**             | "How many close friends do you have?"                                                                      | 0 = None, 1 or more = Yes                               |
| **Psychological distress**    | Defined as feeling lonely, being unable to sleep due to worry, or planning a suicide attempt.              | 0 = No, 1 = Yes                                         |

# Plan of Analysis

The raw datasets of each country identified above were retrieved the GSHS from the surveillance project with the WHO. The raw datasets were then imported into R version 4.4.1 for cleaning up. we used tidyverse packages to achieve this. Once the new cleaned up data was complete, a ‘clean_dataset’ folder was created to identify the six individual countries data. Following the clean datasets of each country, one complete dataset was compiled to reflect the whole sample for analysis.

# Application of Analyses

The main analysis for this research will be conducted using a combination of Pearson’s correlation, multiple regression, and logistic regression to explore the associations between mental, social, and lifestyle behaviors with physical outbursts in adolescence. First, Pearson's correlation will assess the strength and direction of the linear relationships between variables such as psychological distress, bullying, and substance use with physical outbursts. Scatterplots with lines of best fit will visualize these relationships, accompanied by r values to quantify the degree of correlation. This will provide a preliminary understanding of how each behavior is associated with physical outbursts.

multiple linear regression will be employed to examine the independent effect of each behavior on physical outbursts while controlling for covariates such as age, gender, and parental monitoring. This will help determine which factors have a significant impact on physical outbursts when other variables are considered. Additionally, logistic regression will be used for binary outcomes, such as whether or not a physical outburst occurred, to calculate odds ratios and identify which behaviors increase the likelihood of these events. Visualizations, including scatterplots and regression output tables, will support the interpretation of results, highlighting key predictors of physical outbursts.
