---
title: 'The Adolescent Emotional Brain and Physical Outbursts'
subtitle: "writeup - PSYC593"
csl: apa.csl
format:
  html:
    embed-resources: true
    self_contained: true 
    output_dir: "../documents"
  pdf: 
    latex-output-dir: "../documents"  
knitr: 
  opts_chunk:
      fig.path: "../results"
editor: source
markdown: 
    wrap: 72
author: Maddy and Biraj
date: today
---

# Background

According to the World Health Organization (WHO), adolescence is defined as a phase of human life between childhood and adulthood ranging in age from 10-19 years. This age of adolescence is an important time for laying a foundation for the good health of youth (Adolescent Health, n.d.). Other sources state that adolescence begins at puberty and ends when individuals assume mature social roles, like employment and parenting. In many developed countries, this transition occurs later, suggesting a longer duration of the adolescent period may be more fitting. However, the start and end points can vary widely across cultures and individuals.It is agreed upon that adolescence is a developmental stage of human life characterized by increased autonomy, the formation of identity, the establishment of social circles, and risk-taking behaviors among individuals. 

Research indicates that adolescent violence is a significant global public health issue. During this period, emotions often take precedence over rational decision-making, leading adolescents to make choices that can profoundly affect their biopsychosocial well-being and shape their perceptions of reality. Those who engage in physical fighting are at an elevated risk for both physical and emotional health problems. Participation in fighting or physical outbursts can be viewed as part of a broader pattern of risky behaviors, which carry serious health implications (Jaworska & MacQueen, 2015; Pringle et al., 2016; Shaikh et al., 2019; Walsh et al., 2013).

During this period, adolescents undergo a developmental transition to adulthood that involves rapid changes in both the brain and body, often occurring at different rates. This time is crucial for a healthy exploration of identity and learning independence. However, it can also be stressful and challenging due to these swift changes. Adolescents develop a stronger sense of right and wrong, along with an understanding of consequences and legal implications. This heightened awareness can lead to risk-taking behaviors, such as underage drinking or drug use, physical fighting, for exampple (Adolescent Development | Youth.Gov, n.d.). A study conducted by UNICEF suggests that globally, at least one in three adolescents had been in a physical fight in the past 12 months (Sitecontrol, 2014). Research shows that adolescents are significantly influenced by the immediate consequences of their decisions. They frequently engage in risky behaviors, even when they are aware of the potential dangers. A study conducted in Chile found that approximately 13.08% of surveyed students reported being involved in two or more physical fights within the past twelve months (Abio et al., 2020; Balocchini et al., 2013).

Adolescents also experience ongoing emotional states, like anxiety, characterized by fear or stress, while their self-concept and self-esteem are influenced by themselves and their peers. Ultimately, the individual tends to fall into a state of greater vulnerability which becomes more opportune for themselves or others to attack the inner self of their emerging identity. Intervening to support positive health choices during adolescence has the potential to lessen the likelihood of developing a health condition in later life, with possible positive implications for future health service provision and resources (Balocchini et al., 2013).

<!-- This paragraph is quite long and feels a bit abrupt. --> fixed
<!-- Perhaps you would prefer to split into several ones and try to get them to flow better. --> fixed
<!-- There are sex and gender differences reported about several of the behaviors you mention throughout --> not the main focus



# Statement of Problem

Adolescent years are stigmatized as years of bullying (e.g., physical, social, video, emotional), greater risk-taking behavior, evolving mental health disorders (e.g., Major Depressive Disorder), peer pressure, and decreased physical health maintenance (e.g., sleep, diet, exercise, mindfulness). These more negative concepts of adolescence are paired with a greater sense of autonomy, responsibility, and freedoms within this age group. Adolescence may receive a drivers permit and driver’s license, get their first job and earn an income, lead clubs or organizations within school or community systems, volunteer, socialize more frequently with friends, have a romantic relationship, and spend less time in the home. 

It is during these years of riding an emotional roller-coaster of highs and lows, complimented by their environment (e.g., home, school, religious setting) and genetic make up (e.g., family history of mental illness) where negative and abnormal patterns of behavior may take root in the adolescent’s daily life at an exacerbated rate. 

The mental, social, and lifestyle behaviors of adolescents have the potential to negatively or positively impact outward responses to negative stressors in their life. Acting on these negative stressors via physical outbursts can lead to school repercussions (e.g., suspensions, expulsion) or legal difficulties (e.g., being arrested as a minor, possession of illicit substances, disorderly conduct) that can have a lasting effect on the minor's future vocational or educational prospects following adolescent years. Hence, it is critical to investigate what underlying mental, social, and lifestyle behaviors may be associated with physical outbursts, in an effort to mitigate hurdles to educational success and legal troubles. 

<!-- Did not know what the problem is after reading this section. --> statement of problem in last paragraph


# Research Question

Therefore, our research question seeks to understand if reported mental (e.g., suicidal ideation, loneliness), social (e.g., bullying) and lifestyle behaviors (e.g., drug and alcohol use) are associated with physical outbursts. Physical outbursts are at the crux of high emotionality and adolescence is the period in human development where it becomes the melting pot of many environmental challenges while individual behaviors are put to the test. The specific research question, is: **Are mental, social, and lifestyle behaviors associated with physical outbursts in adolescence?**

<!-- The question is clear.  --> done


# Data

The sample dataset in which this research question will be asked is with from the Global School-Based Student Health Survey (GSHS) from Afghanistan, Bangladesh, Bhutan, The Maldives, Nepal, and Sri Lanka. This was a collaborative surveillance project between the selected national governments and the World Health Organization (WHO) to help countries measure and assess the behavioral risk factors and protective factors in the adolescent population aged 13 to 17 years.

# Variables Description
The table below describes each variable, the question asked, and how the question was measured. All of the following questions were forced choice as a ‘yes’ or ‘no’ question or on a Likert scale. The following table outlines the variables that will be used in the analysis, the survey questions they correspond to, and the recoding method used:

<!-- In the table below, it would be useful to also indicate whether the variable belongs to one of your -->
<!-- analysis categories (mental, social, or lifestyle behaviors, or physical outbursts. -->
<!-- Also, if there are other variables. What role will they play in answering your question? -->
Demographic variables for age are categorized into four groups "11 years old or younger," "12 to 14 years," "15 to 17 years," and "18 years old or older." This categorization ensures consistency in analysis, as the original data set presents age both categorically for those 11 years or younger, 18 years and older, and continuously for ages 12 to 17. Mental health indicators are coded as a binary code of 0 for responses of "never" or "rarely," and 1 for responses indicating "sometimes," "most of the time," or "always." Sleep issues are similarly coded, with 0 representing "never/rarely" and 1 for "sometimes/most of the time/always." For suicide-related variables, the coding "considered suicide variable " is coded as 0 for "no" and 1 for "yes"; "made suicide plan variables" is coded as 0 for "no" and 1 for "yes"; and "attempted suicide" is coded as 0 for "0 times" and 1 for "1 or more times." 

Substance use-related variables i.e current smoking status, coded as 0 for "no smoking" and 1 for "any smoking in the past 30 days." Other tobacco use follows similar coding as smoking status. Frequency categories for use of substance are coded as "never" (0 days), "sometimes" (1 to 9 days), "most of the time" (10 to 19 days), and "every day" (20 or more days). For marijuana use, it is a binary indicator coded as 0 for "never" and 1 for "any use," with frequency categories as follows: "never," "sometimes" (1 to 9 times), "most of the time" (10 to 19 times), and "every day" (20 or more times). 

Social support indicators include parent understanding, coded as 0 for "never/rarely/sometimes" and 1 for "most of the time/always." Parental awareness of activities is coded as 0 for "never/rarely/sometimes" and 1 for "most of the time/always." Peer support scores are binary coded as 0 for "never/rarely/sometimes" and 1 for "most of the time/always." Bullying experiences are recorded into two categories: "0 days" and "1 or more times."



| Variable                      | Survey Question                                                                                            | Recoding                                                |
|----------------|-------------------------------|--------------------------|
| **Parents understanding**     | "During the past 30 days, how often did your parents/guardians understand your problems and worries?"      | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Parents monitoring**        | "During the past 30 days, how often did your parents/guardians know what you were doing with free time?"   | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Parents check homework**    | "During the past 30 days, how often did your parents/guardians check if your homework was done?"           | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Parents Control**           | "During the past 30 days, how often did your parents/guardians go through your things without permission?" | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Gender**                    | "What is your sex?"                                                                                        | 1 = Male, 2 = Female                                    |
| **Age**                       | "How old are you?"                                                                                         | 13-15 = 1, 16-17 = 2                                    |
| **Current cigarette smoking** | "During the past 30 days, on how many days did you smoke cigarettes?"                                      | 0 = No, 1 or more = Yes                                 |
| **Currently drank alcohol**   | "During the past 30 days, how many drinks did you usually drink per day?"                                  | 0 = No, 1 or more = Yes                                 |
| **Currently used marijuana**  | "During the past 30 days, how many times have you used marijuana?"                                         | 0 = No, 1 or more = Yes                                 |
| **Ever used amphetamines**    | "During your life, how many times have you used amphetamines or methamphetamines?"                         | 0 = No, 1 or more = Yes                                 |
| **Physical Activity**         | "During the past 7 days, how many days were you physically active for at least 60 minutes?"                | 0 = No, 1 or more days = Yes                            |
| **PE Class Attendance**       | "During this school year, how many days did you attend physical education (PE) class each week?"           | 0 = No, 1 or more days = Yes                            |
| **Sedentary behavior**        | "How much time do you spend watching TV, playing games, or talking with friends daily?"                    | Less than 1-2 hours = No, 3 or more hours = Yes         |
| **Supportive friends**        | "During the past 30 days, how often were students kind and helpful?"                                       | 1 = Most of the time/always, 0 = Never/rarely/sometimes |
| **Close friends**             | "How many close friends do you have?"                                                                      | 0 = None, 1 or more = Yes                               |
| **Psychological distress**    | Defined as feeling lonely, being unable to sleep due to worry, or planning a suicide attempt.              | 0 = No, 1 = Yes                                         |

# Plan of Analysis

Our main dependent variable, physical outbursts, originally were reported on a Likert scale and stratified by the number of physical outbursts from 0, 1-2, 2-3, 4-5, 6-7, 8-9, 10-11, or 12+ times. To conduct our analysis, we will transfer this categorical variable into a binary variable describing no physical outbursts (0) versus any physical outbursts (1-12+). Following, this binary variable of physical outbursts will be correlated with social support, substance use, mental health, and physical activity variables. This data analysis will explain if any relationship exists between physical outbursts and the mental, social, and lifestyle bevaiors provided above. 

Survey weights and stata will be added and designed as a survey analysis. 

The raw datasets of each country identified above were retrieved the GSHS from the surveillance project with the WHO. The raw datasets were then imported into R version 4.4.1 for cleaning up. we used tidyverse packages to achieve this. Once the new cleaned up data was complete, a ‘clean_dataset’ folder was created to identify the six individual countries data. Following the clean datasets of each country, one complete dataset was compiled to reflect the whole sample for analysis.


<!-- I see you have made use of the labeling of the variables in your cleaned data set. --> great
<!-- It seems you forgot to actually save the tidied data set for the analyses  --> fixing


## Application of Analyses

<!-- This probably should be a subsection of the Plan of analysis section. You can nest headings in markdown by using more # signs at the beginning --> fixed?

The main analysis for this research will be conducted using a combination of Pearson’s correlation, multiple regression, and logistic regression to explore the associations between mental, social, and lifestyle behaviors with physical outbursts in adolescence. First, Pearson's correlation will assess the strength and direction of the linear relationships between variables such as psychological distress, bullying, and substance use with physical outbursts. Scatter plots with lines of best fit will visualize these relationships, accompanied by r values to quantify the degree of correlation. This will provide a preliminary understanding of how each behavior is associated with physical outbursts.

Multiple linear regression will be employed to examine the independent effect of each behavior on physical outbursts while controlling for covariates such as age, gender, and parental monitoring. This will help determine which factors have a significant impact on physical outbursts when other variables are considered. Additionally, logistic regression will be used for binary outcomes, such as whether or not a physical outburst occurred, to calculate odds ratios and identify which behaviors increase the likelihood of these events. Visualizations, including scatter plots and regression output tables, will support the interpretation of results, highlighting key predictors of physical outbursts.


<!-- What will be your initial approach for relations that include a binary variable? -->

<!-- Since you will be fitting some regression models, both linear and logistic, you may be interested in looking into -->
<!-- the visualization capabilities of packages such as marginaleffects --> comment



#Ref:

Nationally Representative Sample of Adolescents in Chile. Frontiers in Public Health, 8. https://doi.org/10.3389/fpubh.2020.00046
Adolescent Development | Youth.gov. (n.d.). Retrieved November 5, 2024, from https://youth.gov/youth-topics/adolescent-health/adolescent-development
Adolescent health. (n.d.). Retrieved November 5, 2024, from https://www.who.int/health-topics/adolescent-health
Balocchini, E., Chiamenti, G., & Lamborghini, A. (2013). Adolescents: Which risks for their life and health? Journal of Preventive Medicine and Hygiene, 54(4), 191.
Jaworska, N., & MacQueen, G. (2015). Adolescence as a unique developmental period. Journal of Psychiatry & Neuroscience : JPN, 40(5), 291. https://doi.org/10.1503/jpn.150268
Pringle, J., Mills, K., McAteer, J., Jepson, R., Hogg, E., Anand, N., & Blakemore, S.-J. (2016). A systematic review of adolescent physiological development and its relationship with health-related behaviour: A protocol. Systematic Reviews, 5(1), 3. https://doi.org/10.1186/s13643-015-0173-5
Shaikh, M. A., Abio, A., Celedonia, K. L., & Lowery Wilson, M. (2019). Physical Fighting among School-Attending Adolescents in Pakistan: Associated Factors and Contextual 

